### PR TITLE
folders: update folders structure

### PR DESCRIPTION
**Pull request by thiagommedeiros**
This PR is a new folder structure proposal. 
Please, let's discuss if it makes sense. 

I suggest you get the `improve-folder-structure` branch and open the project on your code editor to see better these changes.

### Renames the following `containers`:
  - CheckoutContainer to Checkout
  - AddressFormContainer to AddressForm

### Moves the following `containers` to `/pages` folder and rename them:
  - BillingContainer to Billing
  - CustomerContainer to Customer
  - PaymentContainer to Payment
  - ShippingContainer to Shipping

### It also:
- Renames the '/helper' folder to '/utils'
- Moves the '/api' folder to '/utils'
- ~~Renames the '/theme-pagarme' folder to 'default' and move it to '/themes' folder~~

### CODE REVIEW

**Comment by GitCop** [comment]
Os seguintes commits de seu Pull Request precisam de ajustes no título:

 * Commit: 72f5c2190e57377f59eda0096346a6d6e4ca9eca
  * Your commit message body contains a line that is longer than 72 characters

O guia completo de estilo de commits está disponível em https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by vcapretz** [comment]
> Renames the following containers: 
thanks for that!!! ahahhaha really makes sense, it's inside a containers folder, what should it be? no need to specify again on the container name

> It also: 
nice changes! except for `Renames the '/theme-pagarme' folder to 'default' and move it to '/themes' folder`, because I don't think we should handle it right now, the guys on the Pilot project are structuring their project to use Yarn Workspaces (which is really great!) and the `theme` is something that changes, as it can be imported from a project on `npm`, for instance. So I would keep the original `theme-pagarme` and wait for a final change here. 

the rest is fine!

**Comment by thiagommedeiros** [comment]
@vcapretz Good point! I'll rollback the themes folder changes.

**Comment by augusto-jm-amaral** [comment]
Nice PR @thiagommedeiros, has some conflicts.

**Comment by thiagommedeiros** [comment]
Done @augusto-jm-amaral

**Pull request merged**
