### PR TITLE
Theme strategy

### LINKED ISSUE #9: Implementar estratégia de tema
Pretendemos usar a seguinte lib para `theming`: https://github.com/javivelasco/react-css-themr

### LINKED ISSUE #78: Corrigir styles do componente Button

### PR DESCRIPTION
**Pull request by vcapretz**
Closes #9 
closes #78  

We're adding a theme strategy according to the [pilot](https://github.com/pagarme/pilot) project, where we'll have our own themes but users can create and use their own

we need to review the styling to check for inconsistencies with Zeplin

### CODE REVIEW

**Comment by augusto-jm-amaral** [comment]
Tem uns problemas de lint @vcapretz

**Comment by vcapretz** [comment]
fixed @augusto-jm-amaral

**Comment by augusto-jm-amaral** [comment]
nossa tem conflito em :frowning:

**Comment by augusto-jm-amaral** [comment]
Ficou muito bom @vcapretz  :tada:

**Pull request closed without merging**
